-- Baslangic semasi (Flyway baseline). Entity'lerle birebir; Hibernate ddl-auto:validate ile dogrular.
-- Mevcut DB'ler baseline-on-migrate ile bu surumu atlar (zaten ddl-auto ile olusturulmustur).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE alarms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    symbol       VARCHAR(255) NOT NULL,
    target_price NUMERIC(38, 18) NOT NULL,
    direction    VARCHAR(255) NOT NULL,
    type         VARCHAR(255),
    is_active    BOOLEAN NOT NULL,
    sort_order   INTEGER,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    triggered_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE paper_accounts (
    user_id      BIGINT PRIMARY KEY,
    usdt_balance NUMERIC(38, 8) NOT NULL
);

CREATE TABLE paper_positions (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    asset     VARCHAR(255) NOT NULL,
    qty       NUMERIC(38, 8) NOT NULL,
    avg_price NUMERIC(38, 8) NOT NULL,
    CONSTRAINT uq_position_user_asset UNIQUE (user_id, asset)
);

CREATE TABLE paper_orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    symbol     VARCHAR(255) NOT NULL,
    side       VARCHAR(255) NOT NULL,
    type       VARCHAR(255) NOT NULL,
    price      NUMERIC(38, 8),
    qty        NUMERIC(38, 8) NOT NULL,
    status     VARCHAR(255) NOT NULL,
    fill_price NUMERIC(38, 8),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    filled_at  TIMESTAMP(6) WITH TIME ZONE
);

-- Sik kullanilan sorgu desenleri icin indeksler
CREATE INDEX idx_alarms_user_active ON alarms (user_id, is_active);
CREATE INDEX idx_paper_orders_user ON paper_orders (user_id);
CREATE INDEX idx_paper_orders_status_type ON paper_orders (status, type);
CREATE INDEX idx_paper_positions_user ON paper_positions (user_id);
